import { PGlite } from '@electric-sql/pglite';
let t=Date.now();
const db = new PGlite();
await db.waitReady;
console.log('boot', Date.now()-t);
t=Date.now();
await db.exec(`create table t(id uuid primary key default gen_random_uuid(), n text, j jsonb, created_at timestamptz default now()); insert into t(n) select 'x'||g from generate_series(1,1000) g; alter table t enable row level security;`);
console.log('exec', Date.now()-t);
console.log((await db.query('select count(*) from t')).rows, (await db.query('select version()')).rows);
console.log((await db.query("select rolname from pg_roles")).rows.map(r=>r.rolname).join(','));
t=Date.now();
const dump = await db.dumpDataDir('gzip');
console.log('dump', Date.now()-t, dump.size);
t=Date.now();
const db2 = new PGlite({ loadDataDir: dump });
await db2.waitReady;
console.log('load', Date.now()-t, (await db2.query('select count(*) from t')).rows);
await db2.transaction(async tx => { await tx.query("insert into t(n) values('y')"); });
console.log('ok');
